export const TEAM_ZH: Record<string, string> = {
  "Algeria": "阿尔及利亚",
  "Argentina": "阿根廷",
  "Australia": "澳大利亚",
  "Austria": "奥地利",
  "Belgium": "比利时",
  "Bosnia & Herzegovina": "波黑",
  "Bosnia and Herzegovina": "波黑",
  "Brazil": "巴西",
  "Canada": "加拿大",
  "Cape Verde": "佛得角",
  "Chile": "智利",
  "Colombia": "哥伦比亚",
  "Costa Rica": "哥斯达黎加",
  "Croatia": "克罗地亚",
  "Curaçao": "库拉索",
  "Curacao": "库拉索",
  "Czechia": "捷克",
  "Czech Republic": "捷克",
  "DR Congo": "民主刚果",
  "Denmark": "丹麦",
  "Ecuador": "厄瓜多尔",
  "Egypt": "埃及",
  "England": "英格兰",
  "France": "法国",
  "Germany": "德国",
  "Ghana": "加纳",
  "Greece": "希腊",
  "Haiti": "海地",
  "Hungary": "匈牙利",
  "Iran": "伊朗",
  "Iraq": "伊拉克",
  "Italy": "意大利",
  "Ivory Coast": "科特迪瓦",
  "Japan": "日本",
  "Jordan": "约旦",
  "Korea Republic": "韩国",
  "South Korea": "韩国",
  "Mexico": "墨西哥",
  "Morocco": "摩洛哥",
  "Netherlands": "荷兰",
  "New Zealand": "新西兰",
  "Nigeria": "尼日利亚",
  "Norway": "挪威",
  "Panama": "巴拿马",
  "Paraguay": "巴拉圭",
  "Peru": "秘鲁",
  "Poland": "波兰",
  "Portugal": "葡萄牙",
  "Qatar": "卡塔尔",
  "Russia": "俄罗斯",
  "Saudi Arabia": "沙特阿拉伯",
  "Scotland": "苏格兰",
  "Senegal": "塞内加尔",
  "Serbia": "塞尔维亚",
  "Slovakia": "斯洛伐克",
  "Slovenia": "斯洛文尼亚",
  "South Africa": "南非",
  "Spain": "西班牙",
  "Sweden": "瑞典",
  "Switzerland": "瑞士",
  "Tunisia": "突尼斯",
  "Turkey": "土耳其",
  "Turkiye": "土耳其",
  "Ukraine": "乌克兰",
  "Uruguay": "乌拉圭",
  "USA": "美国",
  "United States": "美国",
  "Uzbekistan": "乌兹别克斯坦",
  "Wales": "威尔士",
};

export const TEAM_FLAGS: Record<string, string> = {
  "Algeria": "🇩🇿",
  "Argentina": "🇦🇷",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Belgium": "🇧🇪",
  "Bosnia & Herzegovina": "🇧🇦",
  "Bosnia and Herzegovina": "🇧🇦",
  "Brazil": "🇧🇷",
  "Canada": "🇨🇦",
  "Cape Verde": "🇨🇻",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷",
  "Curaçao": "🇨🇼",
  "Curacao": "🇨🇼",
  "Czechia": "🇨🇿",
  "Czech Republic": "🇨🇿",
  "DR Congo": "🇨🇩",
  "Denmark": "🇩🇰",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "England": "🏴",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Greece": "🇬🇷",
  "Haiti": "🇭🇹",
  "Hungary": "🇭🇺",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Italy": "🇮🇹",
  "Ivory Coast": "🇨🇮",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Korea Republic": "🇰🇷",
  "South Korea": "🇰🇷",
  "Mexico": "🇲🇽",
  "Morocco": "🇲🇦",
  "Netherlands": "🇳🇱",
  "New Zealand": "🇳🇿",
  "Nigeria": "🇳🇬",
  "Norway": "🇳🇴",
  "Panama": "🇵🇦",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  "Scotland": "🏴",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "South Africa": "🇿🇦",
  "Spain": "🇪🇸",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Tunisia": "🇹🇳",
  "Turkey": "🇹🇷",
  "Turkiye": "🇹🇷",
  "Ukraine": "🇺🇦",
  "Uruguay": "🇺🇾",
  "USA": "🇺🇸",
  "United States": "🇺🇸",
  "Uzbekistan": "🇺🇿",
  "Wales": "🏴",
};

export function teamZh(name: string) {
  return TEAM_ZH[name] || name;
}

export function teamFlag(name: string) {
  return TEAM_FLAGS[name] || "";
}

export function formatAsianLine(point?: number) {
  if (point === undefined) return "";

  const sign = point > 0 ? "+" : "";
  const abs = Math.abs(point);
  const whole = Math.trunc(abs);
  const fraction = Number((abs - whole).toFixed(2));

  let text: string;
  if (fraction === 0) text = String(whole);
  else if (fraction === 0.25) text = `${whole}/${whole + 0.5}`;
  else if (fraction === 0.5) text = `${whole + 0.5}`;
  else if (fraction === 0.75) text = `${whole + 0.5}/${whole + 1}`;
  else text = String(abs);

  return `${point < 0 ? "-" : sign}${text}`;
}
